version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8080:80"
    environment:
      - PORT=${PORT}
    depends_on:
      - app_blue
      - app_green
    networks:
      - app_network
    volumes:
      - logs:/var/log/nginx  

  app_blue:
    image: ${BLUE_IMAGE}
    ports:
      - "8081:${PORT}"
    environment:
      - PORT=${PORT}
      - APP_POOL=blue
      - RELEASE_ID=${RELEASE_ID_BLUE}
    networks:
      - app_network

  app_green:
    image: ${GREEN_IMAGE}
    ports:
      - "8082:${PORT}"
    environment:
      - PORT=${PORT}
      - APP_POOL=green
      - RELEASE_ID=${RELEASE_ID_GREEN}
    networks:
      - app_network
      
  alert_watcher:
    build:
      context: .
      dockerfile: Dockerfile.watcher
    container_name: alert_watcher
    env_file:
      - .env
    volumes:
      - logs:/var/log/nginx:ro  
    depends_on:
      - nginx
    networks:
      - app_network

volumes:
  logs:  

networks:
  app_network:
    driver: bridge
